/* lab.js — speech test harness. Standalone; the app never loads this.
 *
 * Trust model, which is the point of the exercise:
 *   - Nothing external is fetched until the user approves that specific asset.
 *   - Every fetched byte is SHA-256 verified against registry.json before use.
 *   - registry.json is generated by pin.sh from Hugging Face's published lfs.oid,
 *     so pinning costs no bandwidth and can be re-run and diffed.
 *   - A hash mismatch aborts and reports both digests. It never falls through.
 */
(function () {
  'use strict';
  var $ = function (id) { return document.getElementById(id); };
  var results = [];

  function record(row) {
    results.push(row);
    $('results').textContent = toMarkdown();
  }
  function toMarkdown() {
    if (!results.length) return 'no runs yet';
    var ua = navigator.userAgent;
    var out = '## Speech Lab — ' + new Date().toISOString() + '\n\n' + ua + '\n\n';
    out += '| test | result | ms |\n|---|---|---|\n';
    results.forEach(function (r) {
      out += '| ' + r.test + ' | ' + String(r.detail).replace(/\|/g, '\\|') + ' | ' + (r.ms == null ? '' : r.ms) + ' |\n';
    });
    return out;
  }

  // ---------------------------------------------------------------- device
  function showDevice() {
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    var rows = [
      ['secure context', window.isSecureContext ? 'yes' : 'NO — mic will be blocked'],
      ['SpeechRecognition', SR ? 'yes' : 'no'],
      ['speechSynthesis', window.speechSynthesis ? 'yes' : 'no'],
      ['WebGPU', navigator.gpu ? 'yes' : 'no'],
      ['AudioWorklet', (window.AudioContext || window.webkitAudioContext) ? 'yes' : 'no'],
      ['SharedArrayBuffer', typeof SharedArrayBuffer !== 'undefined' ? 'yes' : 'no (no threads)'],
      ['crossOriginIsolated', window.crossOriginIsolated ? 'yes' : 'no'],
      ['cores', navigator.hardwareConcurrency || '?'],
      ['deviceMemory', navigator.deviceMemory ? navigator.deviceMemory + ' GB' : 'not exposed'],
      ['standalone PWA', window.matchMedia('(display-mode: standalone)').matches ? 'yes' : 'no (browser tab)']
    ];
    var host = $('device');
    rows.forEach(function (r) {
      var d = document.createElement('div');
      d.className = 'kv';
      var k = document.createElement('span'); k.className = 'k'; k.textContent = r[0];
      var v = document.createElement('span'); v.className = 'v'; v.textContent = String(r[1]);
      d.appendChild(k); d.appendChild(v); host.appendChild(d);
    });
    if (navigator.gpu && navigator.gpu.requestAdapter) {
      navigator.gpu.requestAdapter().then(function (a) {
        if (!a) return;
        var d = document.createElement('div'); d.className = 'kv';
        var k = document.createElement('span'); k.className = 'k'; k.textContent = 'GPU adapter';
        var v = document.createElement('span'); v.className = 'v';
        v.textContent = (a.info && (a.info.vendor || '') + ' ' + (a.info.architecture || '')) || 'available';
        d.appendChild(k); d.appendChild(v); $('device').appendChild(d);
      }).catch(function () {});
    }
  }

  // ---------------------------------------------------------------- 1. STT
  var rec = null, srT0 = 0, srFirstPartial = 0, srFinals = 0;
  function startSR() {
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) { alert('No SpeechRecognition in this browser.'); return; }
    rec = new SR();
    rec.lang = 'en-US';
    rec.interimResults = true;
    rec.continuous = $('sr-continuous').checked;
    rec.maxAlternatives = 1;
    srT0 = performance.now(); srFirstPartial = 0; srFinals = 0;
    $('sr-interim').textContent = ''; $('sr-final').textContent = '';
    $('sr-stats').textContent = 'listening…';

    var emitted = 0;
    rec.onresult = function (e) {
      var interim = '', fresh = '';
      for (var i = 0; i < e.results.length; i++) {
        var r = e.results[i];
        if (r.isFinal) { if (i >= emitted) { fresh += r[0].transcript; emitted = i + 1; } }
        else interim += r[0].transcript;
      }
      if (interim && !srFirstPartial) {
        srFirstPartial = performance.now() - srT0;
        $('sr-stats').textContent = 'first partial: ' + Math.round(srFirstPartial) + ' ms';
      }
      if (interim) $('sr-interim').textContent = interim;
      if (fresh) {
        srFinals++;
        $('sr-final').textContent += (srFinals > 1 ? ' ' : '') + fresh.trim();
        $('sr-interim').textContent = '';
      }
    };
    rec.onerror = function (e) { $('sr-stats').textContent = 'error: ' + (e && e.error); };
    rec.onend = function () {
      $('sr-start').disabled = false; $('sr-stop').disabled = true;
      var txt = $('sr-final').textContent;
      $('sr-stats').textContent = 'ended · ' + srFinals + ' final segment(s) · first partial ' +
        (srFirstPartial ? Math.round(srFirstPartial) + ' ms' : 'none');
      record({ test: 'Web Speech STT', detail: txt || '(nothing)', ms: Math.round(srFirstPartial) });
    };
    rec.start();
    $('sr-start').disabled = true; $('sr-stop').disabled = false;
  }

  // ---------------------------------------------------------------- 2. TTS
  function fillVoices() {
    var sel = $('tts-voice');
    var list = (window.speechSynthesis && speechSynthesis.getVoices()) || [];
    sel.innerHTML = '';
    list.forEach(function (v, i) {
      var o = document.createElement('option');
      o.value = String(i);
      o.textContent = v.name + ' (' + v.lang + ')' + (v.localService === false ? ' — network' : '');
      sel.appendChild(o);
    });
    if (!list.length) { var o = document.createElement('option'); o.textContent = 'no voices yet…'; sel.appendChild(o); }
  }
  function speak() {
    if (!window.speechSynthesis) return;
    var list = speechSynthesis.getVoices();
    var v = list[parseInt($('tts-voice').value, 10)];
    var u = new SpeechSynthesisUtterance($('tts-text').value);
    if (v) { u.voice = v; u.lang = v.lang; }
    var t0 = performance.now(), first = 0;
    u.onstart = function () {
      first = performance.now() - t0;
      $('tts-stats').textContent = 'time to first audio: ' + Math.round(first) + ' ms';
    };
    u.onend = function () {
      var total = Math.round(performance.now() - t0);
      $('tts-stats').textContent = 'first audio ' + Math.round(first) + ' ms · total ' + total + ' ms';
      record({ test: 'TTS ' + (v ? v.name : 'default'), detail: 'ttfa ' + Math.round(first) + ' ms, total ' + total + ' ms', ms: Math.round(first) });
    };
    speechSynthesis.cancel();
    speechSynthesis.speak(u);
  }

  // ---------------------------------------------------------------- 3. VAD
  var vadEvents = 0, vadT0 = 0;
  function startVad() {
    if (!window.App || !App.Vad) { alert('vad.js not loaded'); return; }
    vadEvents = 0; vadT0 = performance.now();
    App.Vad.start({
      onSpeechStart: function () {
        vadEvents++;
        $('vad-stats').textContent = 'speech start #' + vadEvents + ' at ' +
          Math.round(performance.now() - vadT0) + ' ms';
      },
      onSpeechEnd: function () {
        $('vad-stats').textContent += ' · ended ' + Math.round(performance.now() - vadT0) + ' ms';
      },
      onLevel: function (rms, floor, speaking) {
        var pct = Math.min(100, rms * 900);
        $('vad-bar').style.width = pct + '%';
        $('vad-bar').className = speaking ? 'speaking' : '';
        $('vad-floor').style.left = Math.min(100, floor * 900 * 3.5) + '%';
      }
    }).then(function (ok) {
      if (!ok) { $('vad-stats').textContent = 'VAD unavailable (permission or unsupported)'; return; }
      $('vad-start').disabled = true; $('vad-stop').disabled = false;
      $('vad-stats').textContent = 'running — the marker is the speech threshold';
    });
  }

  // ------------------------------------------------- 4. pinned, consented loader
  function hex(buf) {
    var b = new Uint8Array(buf), s = '';
    for (var i = 0; i < b.length; i++) s += b[i].toString(16).padStart(2, '0');
    return s;
  }

  /* Fetch one pinned file and refuse to return it unless the digest matches.
     Streamed into chunks and concatenated once, rather than held twice, because
     materialising a large model as one buffer is what gets iOS tabs killed. */
  function fetchVerified(file, onProgress) {
    return fetch(file.url, { mode: 'cors' }).then(function (resp) {
      if (!resp.ok) throw new Error('HTTP ' + resp.status);
      var total = file.bytes || parseInt(resp.headers.get('content-length') || '0', 10);
      if (!resp.body || !resp.body.getReader) return resp.arrayBuffer();
      var reader = resp.body.getReader(), chunks = [], got = 0;
      return (function pump() {
        return reader.read().then(function (r) {
          if (r.done) {
            var out = new Uint8Array(got), off = 0;
            chunks.forEach(function (c) { out.set(c, off); off += c.length; });
            chunks.length = 0;
            return out.buffer;
          }
          chunks.push(r.value); got += r.value.length;
          if (onProgress && total) onProgress(got / total);
          return pump();
        });
      })();
    }).then(function (buf) {
      return crypto.subtle.digest('SHA-256', buf).then(function (d) {
        var got = hex(d);
        if (got !== file.sha256) {
          throw new Error('HASH MISMATCH for ' + file.path + '\n  expected ' + file.sha256 + '\n  got      ' + got);
        }
        return buf;
      });
    });
  }

  function renderRegistry(reg) {
    var host = $('registry');
    Object.keys(reg.assets).forEach(function (key) {
      var a = reg.assets[key];
      var card = document.createElement('div'); card.className = 'asset';

      var h = document.createElement('div'); h.className = 'asset-head';
      var nm = document.createElement('strong'); nm.textContent = a.label;
      var meta = document.createElement('span'); meta.className = 'meta';
      meta.textContent = a.kind + ' · ' + (a.totalBytes / 1e6).toFixed(1) + ' MB · ' + a.licence;
      h.appendChild(nm); h.appendChild(meta); card.appendChild(h);

      var src = document.createElement('div'); src.className = 'src';
      src.textContent = a.repo; card.appendChild(src);

      a.files.forEach(function (f) {
        var d = document.createElement('div'); d.className = 'file';
        d.textContent = f.path + '  ' + (f.sha256 || 'UNPINNED').slice(0, 24) + '…';
        card.appendChild(d);
      });

      var btn = document.createElement('button');
      btn.className = 'primary';
      btn.textContent = 'Download & verify (' + (a.totalBytes / 1e6).toFixed(0) + ' MB)';
      var status = document.createElement('div'); status.className = 'stats';

      btn.addEventListener('click', function () {
        // Explicit, per-asset consent naming the real cost before any byte moves.
        var msg = 'Download ' + a.label + '?\n\n' +
          (a.totalBytes / 1e6).toFixed(1) + ' MB from huggingface.co\n' +
          a.files.length + ' file(s), each SHA-256 verified before use.\n\n' +
          'On cellular this may be slow and will count against your data.';
        if (!window.confirm(msg)) return;
        btn.disabled = true;
        var t0 = performance.now(), i = 0;
        (function next() {
          if (i >= a.files.length) {
            var ms = Math.round(performance.now() - t0);
            status.textContent = 'verified all ' + a.files.length + ' file(s) in ' + ms + ' ms';
            record({ test: 'download ' + key, detail: 'verified ' + (a.totalBytes / 1e6).toFixed(1) + ' MB', ms: ms });
            btn.disabled = false;
            return;
          }
          var f = a.files[i++];
          status.textContent = 'fetching ' + f.path + '…';
          fetchVerified(f, function (p) {
            status.textContent = 'fetching ' + f.path + ' — ' + Math.round(p * 100) + '%';
          }).then(function () {
            status.textContent = f.path + ' ✓ hash ok';
            next();
          }).catch(function (e) {
            status.textContent = 'FAILED: ' + e.message;
            record({ test: 'download ' + key, detail: 'FAILED ' + e.message, ms: null });
            btn.disabled = false;
          });
        })();
      });

      card.appendChild(btn); card.appendChild(status);
      host.appendChild(card);
    });
  }

  // ---------------------------------------------------------------- boot
  showDevice();
  fillVoices();
  if (window.speechSynthesis) speechSynthesis.onvoiceschanged = fillVoices;
  setTimeout(fillVoices, 1000);

  $('sr-start').addEventListener('click', startSR);
  $('sr-stop').addEventListener('click', function () { if (rec) rec.stop(); });
  $('tts-speak').addEventListener('click', speak);
  $('vad-start').addEventListener('click', startVad);
  $('vad-stop').addEventListener('click', function () {
    App.Vad.stop();
    $('vad-start').disabled = false; $('vad-stop').disabled = true;
    $('vad-stats').textContent = 'stopped after ' + vadEvents + ' speech event(s)';
    record({ test: 'VAD', detail: vadEvents + ' speech events', ms: null });
  });
  $('copy-results').addEventListener('click', function () {
    var t = toMarkdown();
    if (navigator.clipboard) navigator.clipboard.writeText(t);
  });

  fetch('registry.json').then(function (r) { return r.json(); })
    .then(renderRegistry)
    .catch(function (e) { $('registry').textContent = 'registry.json failed to load: ' + e.message; });
})();
