/* lab.js — speech test harness. Standalone; the app never loads this.
 *
 * Trust model, which is the point of the exercise:
 *   - Nothing external is fetched until the user approves that specific asset.
 *   - Every fetched byte is SHA-256 verified against registry.json before use.
 *   - registry.json is generated by pin.sh from Hugging Face's published lfs.oid,
 *     so pinning costs no bandwidth and can be re-run and diffed.
 *   - A hash mismatch aborts and reports both digests. It never falls through.
 */
(function () {
  'use strict';
  var $ = function (id) { return document.getElementById(id); };
  var results = [];

  // Build an element with textContent, never innerHTML — voice names and model
  // paths are third-party strings and this page renders plenty of them.
  function make(tag, className, text) {
    var n = document.createElement(tag);
    if (className) n.className = className;
    if (text != null) n.textContent = text;
    return n;
  }

  function record(row) {
    results.push(row);
    $('results').textContent = toMarkdown();
  }
  function toMarkdown() {
    if (!results.length) return 'no runs yet';
    var ua = navigator.userAgent;
    var out = '## Speech Lab — ' + new Date().toISOString() + '\n\n' + ua + '\n\n';
    out += '| test | result | ms |\n|---|---|---|\n';
    results.forEach(function (r) {
      out += '| ' + r.test + ' | ' + String(r.detail).replace(/\|/g, '\\|') + ' | ' + (r.ms == null ? '' : r.ms) + ' |\n';
    });
    return out;
  }

  // ---------------------------------------------------------------- device
  function showDevice() {
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    var rows = [
      ['secure context', window.isSecureContext ? 'yes' : 'NO — mic will be blocked'],
      ['SpeechRecognition', SR ? 'yes' : 'no'],
      ['speechSynthesis', window.speechSynthesis ? 'yes' : 'no'],
      ['WebGPU', navigator.gpu ? 'yes' : 'no'],
      ['AudioWorklet', (window.AudioContext || window.webkitAudioContext) ? 'yes' : 'no'],
      ['SharedArrayBuffer', typeof SharedArrayBuffer !== 'undefined' ? 'yes' : 'no (no threads)'],
      ['crossOriginIsolated', window.crossOriginIsolated ? 'yes' : 'no'],
      ['cores', navigator.hardwareConcurrency || '?'],
      ['deviceMemory', navigator.deviceMemory ? navigator.deviceMemory + ' GB' : 'not exposed'],
      ['standalone PWA', window.matchMedia('(display-mode: standalone)').matches ? 'yes' : 'no (browser tab)']
    ];
    var host = $('device');
    rows.forEach(function (r) {
      var d = document.createElement('div');
      d.className = 'kv';
      var k = document.createElement('span'); k.className = 'k'; k.textContent = r[0];
      var v = document.createElement('span'); v.className = 'v'; v.textContent = String(r[1]);
      d.appendChild(k); d.appendChild(v); host.appendChild(d);
    });
    if (navigator.gpu && navigator.gpu.requestAdapter) {
      navigator.gpu.requestAdapter().then(function (a) {
        if (!a) return;
        var d = document.createElement('div'); d.className = 'kv';
        var k = document.createElement('span'); k.className = 'k'; k.textContent = 'GPU adapter';
        var v = document.createElement('span'); v.className = 'v';
        v.textContent = (a.info && (a.info.vendor || '') + ' ' + (a.info.architecture || '')) || 'available';
        d.appendChild(k); d.appendChild(v); $('device').appendChild(d);
      }).catch(function () {});
    }
  }

  // ---------------------------------------------------------------- 1. STT
  var rec = null, srT0 = 0, srFirstPartial = 0, srFinals = 0;
  function startSR() {
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) { alert('No SpeechRecognition in this browser.'); return; }
    rec = new SR();
    rec.lang = 'en-US';
    rec.interimResults = true;
    rec.continuous = $('sr-continuous').checked;
    rec.maxAlternatives = 1;
    srT0 = performance.now(); srFirstPartial = 0; srFinals = 0;
    $('sr-interim').textContent = ''; $('sr-final').textContent = '';
    $('sr-stats').textContent = 'listening…';

    var emitted = 0;
    rec.onresult = function (e) {
      var interim = '', fresh = '';
      for (var i = 0; i < e.results.length; i++) {
        var r = e.results[i];
        if (r.isFinal) { if (i >= emitted) { fresh += r[0].transcript; emitted = i + 1; } }
        else interim += r[0].transcript;
      }
      if (interim && !srFirstPartial) {
        srFirstPartial = performance.now() - srT0;
        $('sr-stats').textContent = 'first partial: ' + Math.round(srFirstPartial) + ' ms';
      }
      if (interim) $('sr-interim').textContent = interim;
      if (fresh) {
        srFinals++;
        $('sr-final').textContent += (srFinals > 1 ? ' ' : '') + fresh.trim();
        $('sr-interim').textContent = '';
      }
    };
    rec.onerror = function (e) { $('sr-stats').textContent = 'error: ' + (e && e.error); };
    rec.onend = function () {
      $('sr-start').disabled = false; $('sr-stop').disabled = true;
      var txt = $('sr-final').textContent;
      $('sr-stats').textContent = 'ended · ' + srFinals + ' final segment(s) · first partial ' +
        (srFirstPartial ? Math.round(srFirstPartial) + ' ms' : 'none');
      record({ test: 'Web Speech STT', detail: txt || '(nothing)', ms: Math.round(srFirstPartial) });
    };
    rec.start();
    $('sr-start').disabled = true; $('sr-stop').disabled = false;
  }

  // ---------------------------------------------------------------- 2. voice bench
  var shortlist = [], voiceCache = [], abTimer = null;

  function voices() {
    var all = (window.speechSynthesis && speechSynthesis.getVoices()) || [];
    if (!$('tts-en-only') || !$('tts-en-only').checked) return all;
    return all.filter(function (v) { return /^en/i.test(v.lang); });
  }

  function fillVoices() {
    var sel = $('tts-voice'), list = voices();
    var keep = sel.value;
    voiceCache = list;
    sel.innerHTML = '';
    list.forEach(function (v, i) {
      var o = document.createElement('option');
      o.value = String(i);
      // localService===false means a network voice, which is usually the good one.
      o.textContent = v.name + ' (' + v.lang + ')' + (v.localService === false ? ' — HQ' : '');
      sel.appendChild(o);
    });
    if (!list.length) {
      var o = document.createElement('option');
      o.textContent = 'no voices yet — Android often needs a few seconds';
      sel.appendChild(o);
    }
    if (keep && sel.querySelector('option[value="' + keep + '"]')) sel.value = keep;
  }

  /* Speak one line and resolve when it finishes, so callers can sequence. */
  function say(voice, text, onFirst) {
    return new Promise(function (resolve) {
      if (!window.speechSynthesis) return resolve(null);
      var u = new SpeechSynthesisUtterance(text);
      if (voice) { u.voice = voice; u.lang = voice.lang; }
      var t0 = performance.now(), first = 0;
      u.onstart = function () { first = performance.now() - t0; if (onFirst) onFirst(first); };
      u.onend = function () { resolve({ first: Math.round(first), total: Math.round(performance.now() - t0) }); };
      u.onerror = function () { resolve(null); };
      speechSynthesis.speak(u);
    });
  }

  function stopSpeaking() {
    if (abTimer) { clearTimeout(abTimer); abTimer = null; }
    if (window.speechSynthesis) speechSynthesis.cancel();
    $('tts-stats').textContent = 'stopped';
  }

  function speakOne() {
    var v = voiceCache[parseInt($('tts-voice').value, 10)];
    var text = $('tts-phrase').value;
    speechSynthesis.cancel();
    say(v, text, function (f) {
      $('tts-stats').textContent = (v ? v.name : 'default') + ' — first audio ' + Math.round(f) + ' ms';
    }).then(function (r) {
      if (!r) return;
      $('tts-stats').textContent = (v ? v.name : 'default') + ' — first audio ' + r.first +
        ' ms · total ' + r.total + ' ms' + (v && v.localService === false ? ' · network voice' : ' · on-device');
      record({ test: 'voice ' + (v ? v.name : 'default'), detail: r.total + ' ms total', ms: r.first });
    });
  }

  /* Sequential pass over every voice, announcing each by name first so you can
     tell them apart without watching the screen — which is the point, since you
     will be using this with the phone on a bench. */
  function playAll() {
    var list = voices(), text = $('tts-phrase').value, i = 0;
    speechSynthesis.cancel();
    (function next() {
      if (i >= list.length) { $('tts-stats').textContent = 'played ' + list.length + ' voices'; return; }
      var v = list[i++];
      $('tts-voice').value = String(i - 1);
      $('tts-stats').innerHTML = '';
      var lbl = make('span', 'voice-now', i + '/' + list.length + '  ' + v.name);
      $('tts-stats').appendChild(lbl);
      say(v, v.name.split(/[ (]/)[0] + '. ' + text).then(function (r) {
        if (r) record({ test: 'voice ' + v.name, detail: r.total + ' ms', ms: r.first });
        next();
      });
    })();
  }

  function renderShortlist() {
    var host = $('tts-shortlist');
    host.innerHTML = '';
    shortlist.forEach(function (name, idx) {
      var chip = make('span', 'chip', name);
      var x = make('button', null, '✕');
      x.type = 'button';
      x.addEventListener('click', function () { shortlist.splice(idx, 1); renderShortlist(); });
      chip.appendChild(x);
      host.appendChild(chip);
    });
    $('tts-ab').disabled = shortlist.length < 2;
  }

  function starCurrent() {
    var v = voiceCache[parseInt($('tts-voice').value, 10)];
    if (!v) return;
    if (shortlist.indexOf(v.name) === -1) shortlist.push(v.name);
    renderShortlist();
  }

  /* Alternate the shortlist so you hear them back to back. Differences that are
     obvious in A/B are inaudible when the samples are a minute apart. */
  function abCompare() {
    var all = (window.speechSynthesis && speechSynthesis.getVoices()) || [];
    var picked = shortlist.map(function (n) {
      return all.filter(function (v) { return v.name === n; })[0];
    }).filter(Boolean);
    if (picked.length < 2) return;
    var text = $('tts-phrase').value, i = 0, rounds = 0;
    speechSynthesis.cancel();
    (function next() {
      if (rounds >= picked.length * 2) { $('tts-stats').textContent = 'A/B done'; return; }
      var v = picked[i % picked.length];
      i++; rounds++;
      $('tts-stats').innerHTML = '';
      $('tts-stats').appendChild(make('span', 'voice-now', String.fromCharCode(65 + ((i - 1) % picked.length)) + ' — ' + v.name));
      say(v, text).then(function () { abTimer = setTimeout(next, 350); });
    })();
  }

  // ---------------------------------------------------------------- 3. VAD
  var vadEvents = 0, vadT0 = 0;
  function startVad() {
    if (!window.App || !App.Vad) { alert('vad.js not loaded'); return; }
    vadEvents = 0; vadT0 = performance.now();
    App.Vad.start({
      onSpeechStart: function () {
        vadEvents++;
        $('vad-stats').textContent = 'speech start #' + vadEvents + ' at ' +
          Math.round(performance.now() - vadT0) + ' ms';
      },
      onSpeechEnd: function () {
        $('vad-stats').textContent += ' · ended ' + Math.round(performance.now() - vadT0) + ' ms';
      },
      onLevel: function (rms, floor, speaking) {
        var pct = Math.min(100, rms * 900);
        $('vad-bar').style.width = pct + '%';
        $('vad-bar').className = speaking ? 'speaking' : '';
        $('vad-floor').style.left = Math.min(100, floor * 900 * 3.5) + '%';
      }
    }).then(function (ok) {
      if (!ok) { $('vad-stats').textContent = 'VAD unavailable (permission or unsupported)'; return; }
      $('vad-start').disabled = true; $('vad-stop').disabled = false;
      $('vad-stats').textContent = 'running — the marker is the speech threshold';
    });
  }

  // ------------------------------------------------- 1b. WER against a target
  // Phrases chosen to match what is actually said mid-workout: numbers, weights,
  // exercise names and one-word answers — the cases generic WER benchmarks miss.
  var PHRASES = [
    'yes',
    'no that was the last set',
    'three sets of ten at one thirty five',
    'romanian deadlift four sets of eight at twenty kilos',
    'I did a twenty minute run and my left shoulder is tweaky',
    'start a ninety second rest timer',
    'bench press eight reps then two more at one eighty five'
  ];
  function norm(s) {
    return String(s || '').toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(Boolean);
  }
  // Standard Levenshtein over word tokens: WER = (S+D+I)/N.
  function wer(refStr, hypStr) {
    var r = norm(refStr), h = norm(hypStr);
    if (!r.length) return { wer: null, n: 0 };
    var prev = new Array(h.length + 1), cur = new Array(h.length + 1), i, j;
    for (j = 0; j <= h.length; j++) prev[j] = j;
    for (i = 1; i <= r.length; i++) {
      cur[0] = i;
      for (j = 1; j <= h.length; j++) {
        cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (r[i - 1] === h[j - 1] ? 0 : 1));
      }
      for (j = 0; j <= h.length; j++) prev[j] = cur[j];
    }
    return { wer: prev[h.length] / r.length, n: r.length, edits: prev[h.length] };
  }

  var werRec = null, werT0 = 0, werFirst = 0;
  function startWer() {
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) { alert('No SpeechRecognition here.'); return; }
    var target = $('wer-phrase').value;
    $('wer-target').textContent = target;
    $('wer-heard').textContent = '';
    $('wer-stats').textContent = 'listening…';
    werRec = new SR();
    werRec.lang = 'en-US'; werRec.interimResults = true; werRec.continuous = true; werRec.maxAlternatives = 1;
    werT0 = performance.now(); werFirst = 0;
    var heard = '', emitted = 0;
    werRec.onresult = function (e) {
      var interim = '', fresh = '';
      for (var i = 0; i < e.results.length; i++) {
        var r = e.results[i];
        if (r.isFinal) { if (i >= emitted) { fresh += r[0].transcript; emitted = i + 1; } }
        else interim += r[0].transcript;
      }
      if (!werFirst && (interim || fresh)) werFirst = performance.now() - werT0;
      if (fresh) heard += (heard ? ' ' : '') + fresh.trim();
      $('wer-heard').textContent = heard + (interim ? ' [' + interim + ']' : '');
    };
    werRec.onend = function () {
      $('wer-start').disabled = false; $('wer-stop').disabled = true;
      var res = wer(target, heard);
      var pct = res.wer == null ? '?' : (res.wer * 100).toFixed(0) + '%';
      var noisy = noiseNode ? ' · WITH NOISE (' + $('noise-kind').value + ' @ ' + $('noise-level').value + ')' : ' · quiet';
      $('wer-stats').textContent = 'WER ' + pct + ' (' + res.edits + ' edits / ' + res.n + ' words) · first result ' +
        Math.round(werFirst) + ' ms' + noisy;
      record({ test: 'WER' + noisy, detail: pct + ' — heard: ' + (heard || '(nothing)'), ms: Math.round(werFirst) });
    };
    werRec.onerror = function (e) { $('wer-stats').textContent = 'error: ' + (e && e.error); };
    werRec.start();
    $('wer-start').disabled = true; $('wer-stop').disabled = false;
  }

  // ------------------------------------------------- 1c. gym-noise generator
  var noiseCtx = null, noiseNode = null, noiseGain = null, clankTimer = null;
  function makeNoiseBuffer(ctx, kind) {
    var len = ctx.sampleRate * 2, buf = ctx.createBuffer(1, len, ctx.sampleRate), d = buf.getChannelData(0);
    if (kind === 'white') {
      for (var i = 0; i < len; i++) d[i] = Math.random() * 2 - 1;
    } else {
      // Voss-McCartney-ish pink: closer to gym HVAC and crowd rumble than white.
      var b0 = 0, b1 = 0, b2 = 0;
      for (var j = 0; j < len; j++) {
        var w = Math.random() * 2 - 1;
        b0 = 0.99765 * b0 + w * 0.0990460;
        b1 = 0.96300 * b1 + w * 0.2965164;
        b2 = 0.57000 * b2 + w * 1.0526913;
        d[j] = (b0 + b1 + b2 + w * 0.1848) * 0.25;
      }
    }
    return buf;
  }
  function startNoise() {
    noiseCtx = noiseCtx || new (window.AudioContext || window.webkitAudioContext)();
    if (noiseCtx.state === 'suspended') noiseCtx.resume();
    var kind = $('noise-kind').value;
    noiseGain = noiseCtx.createGain();
    noiseGain.gain.value = parseInt($('noise-level').value, 10) / 100 * 0.4;
    noiseGain.connect(noiseCtx.destination);
    if (kind === 'clank') {
      // Impulsive metallic hits — the hard case, because they look like speech onsets to a VAD.
      clankTimer = setInterval(function () {
        var o = noiseCtx.createOscillator(), g = noiseCtx.createGain();
        o.type = 'triangle';
        o.frequency.value = 900 + Math.random() * 2200;
        var t = noiseCtx.currentTime;
        g.gain.setValueAtTime(0.0001, t);
        g.gain.exponentialRampToValueAtTime(0.6, t + 0.005);
        g.gain.exponentialRampToValueAtTime(0.0001, t + 0.35);
        o.connect(g); g.connect(noiseGain);
        o.start(t); o.stop(t + 0.4);
      }, 900 + Math.random() * 1600);
      noiseNode = { stop: function () {}, disconnect: function () {} };
    } else {
      noiseNode = noiseCtx.createBufferSource();
      noiseNode.buffer = makeNoiseBuffer(noiseCtx, kind);
      noiseNode.loop = true;
      noiseNode.connect(noiseGain);
      noiseNode.start();
    }
    $('noise-toggle').textContent = 'Stop noise';
    $('noise-stats').textContent = 'playing ' + kind + ' — now run 1b or the VAD and see what changes';
  }
  function stopNoise() {
    if (clankTimer) { clearInterval(clankTimer); clankTimer = null; }
    if (noiseNode) { try { noiseNode.stop(); } catch (e) {} try { noiseNode.disconnect(); } catch (e) {} noiseNode = null; }
    if (noiseGain) { try { noiseGain.disconnect(); } catch (e) {} noiseGain = null; }
    $('noise-toggle').textContent = 'Start noise';
    $('noise-stats').textContent = 'stopped';
  }

  // ------------------------------------------------- 4. pinned, consented loader
  function hex(buf) {
    var b = new Uint8Array(buf), s = '';
    for (var i = 0; i < b.length; i++) s += b[i].toString(16).padStart(2, '0');
    return s;
  }

  /* Fetch one pinned file and refuse to return it unless the digest matches.
     Streamed into chunks and concatenated once, rather than held twice, because
     materialising a large model as one buffer is what gets iOS tabs killed. */
  function fetchVerified(file, onProgress) {
    return fetch(file.url, { mode: 'cors' }).then(function (resp) {
      if (!resp.ok) throw new Error('HTTP ' + resp.status);
      var total = file.bytes || parseInt(resp.headers.get('content-length') || '0', 10);
      if (!resp.body || !resp.body.getReader) return resp.arrayBuffer();
      var reader = resp.body.getReader(), chunks = [], got = 0;
      return (function pump() {
        return reader.read().then(function (r) {
          if (r.done) {
            var out = new Uint8Array(got), off = 0;
            chunks.forEach(function (c) { out.set(c, off); off += c.length; });
            chunks.length = 0;
            return out.buffer;
          }
          chunks.push(r.value); got += r.value.length;
          if (onProgress && total) onProgress(got / total);
          return pump();
        });
      })();
    }).then(function (buf) {
      return crypto.subtle.digest('SHA-256', buf).then(function (d) {
        var got = hex(d);
        if (got !== file.sha256) {
          throw new Error('HASH MISMATCH for ' + file.path + '\n  expected ' + file.sha256 + '\n  got      ' + got);
        }
        return buf;
      });
    });
  }

  function renderRegistry(reg) {
    var host = $('registry');
    Object.keys(reg.assets).forEach(function (key) {
      var a = reg.assets[key];
      var card = document.createElement('div'); card.className = 'asset';

      var h = document.createElement('div'); h.className = 'asset-head';
      var nm = document.createElement('strong'); nm.textContent = a.label;
      var meta = document.createElement('span'); meta.className = 'meta';
      meta.textContent = a.kind + ' · ' + (a.totalBytes / 1e6).toFixed(1) + ' MB · ' + a.licence;
      h.appendChild(nm); h.appendChild(meta); card.appendChild(h);

      var src = document.createElement('div'); src.className = 'src';
      src.textContent = a.repo; card.appendChild(src);

      a.files.forEach(function (f) {
        var d = document.createElement('div'); d.className = 'file';
        d.textContent = f.path + '  ' + (f.sha256 || 'UNPINNED').slice(0, 24) + '…';
        card.appendChild(d);
      });

      var btn = document.createElement('button');
      btn.className = 'primary';
      btn.textContent = 'Download & verify (' + (a.totalBytes / 1e6).toFixed(0) + ' MB)';
      var status = document.createElement('div'); status.className = 'stats';

      btn.addEventListener('click', function () {
        // Explicit, per-asset consent naming the real cost before any byte moves.
        var msg = 'Download ' + a.label + '?\n\n' +
          (a.totalBytes / 1e6).toFixed(1) + ' MB from huggingface.co\n' +
          a.files.length + ' file(s), each SHA-256 verified before use.\n\n' +
          'On cellular this may be slow and will count against your data.';
        if (!window.confirm(msg)) return;
        btn.disabled = true;
        var t0 = performance.now(), i = 0;
        (function next() {
          if (i >= a.files.length) {
            var ms = Math.round(performance.now() - t0);
            status.textContent = 'verified all ' + a.files.length + ' file(s) in ' + ms + ' ms';
            record({ test: 'download ' + key, detail: 'verified ' + (a.totalBytes / 1e6).toFixed(1) + ' MB', ms: ms });
            btn.disabled = false;
            return;
          }
          var f = a.files[i++];
          status.textContent = 'fetching ' + f.path + '…';
          fetchVerified(f, function (p) {
            status.textContent = 'fetching ' + f.path + ' — ' + Math.round(p * 100) + '%';
          }).then(function () {
            status.textContent = f.path + ' ✓ hash ok';
            next();
          }).catch(function (e) {
            status.textContent = 'FAILED: ' + e.message;
            record({ test: 'download ' + key, detail: 'FAILED ' + e.message, ms: null });
            btn.disabled = false;
          });
        })();
      });

      card.appendChild(btn); card.appendChild(status);
      host.appendChild(card);
    });
  }

  // ---------------------------------------------------------------- boot
  showDevice();
  fillVoices();
  if (window.speechSynthesis) speechSynthesis.onvoiceschanged = fillVoices;
  setTimeout(fillVoices, 1000);

  PHRASES.forEach(function (p) {
    var o = document.createElement('option'); o.value = p; o.textContent = p; $('wer-phrase').appendChild(o);
  });
  $('wer-target').textContent = PHRASES[0];
  $('wer-phrase').addEventListener('change', function () { $('wer-target').textContent = this.value; });
  $('wer-start').addEventListener('click', startWer);
  $('wer-stop').addEventListener('click', function () { if (werRec) werRec.stop(); });
  $('noise-toggle').addEventListener('click', function () { noiseGain ? stopNoise() : startNoise(); });
  $('noise-level').addEventListener('input', function () {
    if (noiseGain) noiseGain.gain.value = parseInt(this.value, 10) / 100 * 0.4;
  });

  $('sr-start').addEventListener('click', startSR);
  $('sr-stop').addEventListener('click', function () { if (rec) rec.stop(); });
  PHRASES.forEach(function (p) {
    var o = document.createElement('option'); o.value = p; o.textContent = p;
    $('tts-phrase').appendChild(o);
  });
  $('tts-speak').addEventListener('click', speakOne);
  $('tts-all').addEventListener('click', playAll);
  $('tts-star').addEventListener('click', starCurrent);
  $('tts-ab').addEventListener('click', abCompare);
  $('tts-stop').addEventListener('click', stopSpeaking);
  $('tts-en-only').addEventListener('change', fillVoices);
  $('vad-start').addEventListener('click', startVad);
  $('vad-stop').addEventListener('click', function () {
    App.Vad.stop();
    $('vad-start').disabled = false; $('vad-stop').disabled = true;
    $('vad-stats').textContent = 'stopped after ' + vadEvents + ' speech event(s)';
    record({ test: 'VAD', detail: vadEvents + ' speech events', ms: null });
  });
  $('copy-results').addEventListener('click', function () {
    var t = toMarkdown();
    if (navigator.clipboard) navigator.clipboard.writeText(t);
  });

  fetch('registry.json').then(function (r) { return r.json(); })
    .then(renderRegistry)
    .catch(function (e) { $('registry').textContent = 'registry.json failed to load: ' + e.message; });
})();
