#!/usr/bin/env bash
# runs-in: host — fetches bytes to hash them. Nothing is executed or extracted.
#
# Pins the JS/WASM the lab page loads at runtime. jsDelivr is unreachable from
# some sandboxes, which is why this is a separate script you run where it isn't.
#
# Usage:
#   ./pin-js.sh            # pin the default set (ORT + transformers.js)
#   ./pin-js.sh --list     # just show what's in each package's dist/, pin nothing
#
# Writes lab/registry-js.json. Commit it; lab.js verifies against it before
# handing any byte to the runtime.
set -euo pipefail
cd "$(dirname "$0")"

ORT_VER="${ORT_VER:-1.27.0}"
TFJS_VER="${TFJS_VER:-4.2.0}"

# path@version  ->  the files the BROWSER actually fetches.
# ORT: the .mjs is the loader, the .wasm is the binary it instantiates. We take the
# non-jsep build deliberately — jsep carries the WebGPU path, which the research
# found unreliable on mobile WebKit, and it is larger for no gain if we run on WASM.
FILES=(
  "onnxruntime-web@${ORT_VER}|dist/ort.wasm.min.mjs"
  "onnxruntime-web@${ORT_VER}|dist/ort-wasm-simd-threaded.mjs"
  "onnxruntime-web@${ORT_VER}|dist/ort-wasm-simd-threaded.wasm"
  "@huggingface/transformers@${TFJS_VER}|dist/transformers.min.js"
)

list_dist() {
  local pkg="$1"
  echo "== $pkg"
  curl -fsSL --max-time 30 "https://data.jsdelivr.com/v1/packages/npm/${pkg}?structure=flat" \
    | python3 -c "
import json,sys
d=json.load(sys.stdin)
for f in d.get('files',[]):
    n=f['name']
    if n.startswith('/dist/') and (n.endswith('.mjs') or n.endswith('.wasm') or n.endswith('.js')):
        print(f\"   {n:<52}{f.get('size',0)/1e6:>8.2f} MB\")
"
}

if [ "${1:-}" = "--list" ]; then
  list_dist "onnxruntime-web@${ORT_VER}"
  list_dist "@huggingface/transformers@${TFJS_VER}"
  exit 0
fi

tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
echo '{'                                            >  registry-js.json
echo '  "_note": "Generated by pin-js.sh. Verified in-browser before execution.",' >> registry-js.json
echo '  "files": ['                                 >> registry-js.json

first=1
for spec in "${FILES[@]}"; do
  pkg="${spec%%|*}"; path="${spec##*|}"
  url="https://cdn.jsdelivr.net/npm/${pkg}/${path}"
  out="$tmp/$(echo "$path" | tr '/' '_')"
  if ! curl -fsSL --max-time 120 -o "$out" "$url"; then
    echo "  !! FAILED $url  (run --list to see the real dist layout)" >&2
    continue
  fi
  sum=$(sha256sum "$out" | cut -d' ' -f1)
  size=$(stat -c %s "$out")
  [ $first -eq 1 ] || echo ',' >> registry-js.json
  first=0
  printf '    {"pkg": "%s", "path": "%s", "url": "%s", "sha256": "%s", "bytes": %s}' \
    "$pkg" "$path" "$url" "$sum" "$size" >> registry-js.json
  printf '%s  %8.2f MB  %s\n' "${sum:0:16}" "$(echo "$size/1000000" | bc -l)" "$pkg/$path"
done

printf '\n  ]\n}\n' >> registry-js.json
echo "wrote registry-js.json"
