# runs-in: host — metadata only.
import json, urllib.request
ASSETS = {
  "whisper-tiny-en": {"kind":"STT","label":"Whisper tiny.en (int8)","repo":"onnx-community/whisper-tiny.en","licence":"MIT",
    "files":["onnx/encoder_model_quantized.onnx","onnx/decoder_model_merged_quantized.onnx"]},
  "moonshine-tiny": {"kind":"STT","label":"Moonshine tiny (int8)","repo":"onnx-community/moonshine-tiny-ONNX","licence":"MIT",
    "files":["onnx/encoder_model_quantized.onnx","onnx/decoder_model_merged_quantized.onnx"]},
  "kokoro-82m": {"kind":"TTS","label":"Kokoro-82M (int8)","repo":"onnx-community/Kokoro-82M-v1.0-ONNX","licence":"Apache-2.0",
    "files":["onnx/model_quantized.onnx"]},
  "kitten-nano": {"kind":"TTS","label":"KittenTTS nano v0.1","repo":"KittenML/kitten-tts-nano-0.1","licence":"Apache-2.0",
    "files":["kitten_tts_nano_v0_1.onnx","voices.npz"]},
}
def tree(repo, sub):
    url=f"https://huggingface.co/api/models/{repo}/tree/main/{sub}".rstrip('/')
    try:
        with urllib.request.urlopen(url, timeout=30) as r: return json.load(r)
    except Exception: return []
out={"_note":"Generated by pin.sh. sha256 comes from Hugging Face lfs.oid; verified in-browser before use.","assets":{}}
for key,a in ASSETS.items():
    entry={"kind":a["kind"],"label":a["label"],"licence":a["licence"],"repo":a["repo"],"files":[]}
    subs={f.rsplit('/',1)[0] if '/' in f else '' for f in a["files"]}
    index={}
    for s in subs:
        for f in tree(a["repo"], s):
            if isinstance(f,dict) and f.get("path"): index[f["path"]]=f
    for want in a["files"]:
        f=index.get(want)
        if not f: entry["files"].append({"path":want,"sha256":None,"bytes":None,"error":"not found"}); continue
        oid=(f.get("lfs") or {}).get("oid")
        entry["files"].append({"path":want,
            "url":f"https://huggingface.co/{a['repo']}/resolve/main/{want}",
            "sha256":oid,"bytes":f.get("size")})
    entry["totalBytes"]=sum(x["bytes"] or 0 for x in entry["files"])
    out["assets"][key]=entry
print(json.dumps(out,indent=2))
